name: Release GitFlow

on:
  workflow_dispatch:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release GitFlow
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: HDBandit/gitflow-release-action@1.0.5
        with:
          command: start_finish
          tag: 1.1.0
          skip_empty_releases: true