name: Release GitFlow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release GitFlow
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.get_workflow_token.outputs.token }}
      - uses: HDBandit/gitflow-release-action@v1.0.19
        id: release
        with:
          command: start_finish
          tag: ${{ inputs.tag }}
          allow_empty_releases: true
      - name: Print result data
        run: |
          echo "result: ${{ steps.release.outputs.result }}"
          echo "commits: ${{ steps.release.outputs.commits }}"