name: Release GitFlow

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    name: Release GitFlow
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: HDBandit/gitflow-release-action@v1.0.12
        with:
          command: start_finish
          tag: ${{ inputs.tag }}
          allow_empty_releases: false